# Generated by Django 3.2.7 on 2021-10-03 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pokemoncenters',
            new_name='Pokemoncenter',
        ),
    ]
