# Generated by Django 3.2.7 on 2021-10-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_pokemoncenters_pokemoncenter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokemoncenter',
            new_name='ShopingCenter',
        ),
    ]
